### ISSUE TITLE
Running the simulation without learning and gov. interventions

### ISSUE THREAD

**Issue by nivb121** [aws-samples/covid19-simulation#1]
Hi!
I would like to ask if it's possible to run the simulation without the learning phases and without lockdown policies effecting the statistical model?

I want to compare the model's results to past events in the EU

Thank you!

**Comment by vinayhanumaiah** [comment]
Hi @nivb121,

Yes. It's possible. The sample notebook invokes [simulation_orchestrator.py](https://github.com/aws-samples/covid19-simulation/blob/ce569ca7a4eb05c9b379d86847ddcfffd92b6a93/src/simulation_orchestrator.py), which includes the learning phase, and the simulation phase. You can avoid the learning phase by directly invoking [Simulation](https://github.com/aws-samples/covid19-simulation/blob/ce569ca7a4eb05c9b379d86847ddcfffd92b6a93/src/simulation.py#L13) class from [simulation.py](https://github.com/aws-samples/covid19-simulation/blob/master/src/simulation.py).

Let me know if you have further questions.

**Comment by nivb121** [comment]
Hi!
Thank you very much for your reply.
When I tried to run the simulation simply with simulation.py I
encountered troubles with the sim_data object, mostly in the part that
builds the statistics.
How should I run it?

‫בתאריך יום א׳, 17 בינו׳ 2021 ב-8:54 מאת ‪Vinay Hanumaiah‬‏ <‪
notifications@github.com‬‏>:‬
